# Generated by Django 4.2.5 on 2023-10-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='no-avatar.jpg', null=True, upload_to='profiles')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('bio', models.CharField(max_length=50, verbose_name='bio')),
            ],
        ),
    ]
